///////////////////////////////////////////////////////////
//  Event.cs
//  Implementation of the Class Event
//  Generated by Enterprise Architect
//  Created on:      25-Jul-2022 7:42:22 PM
//  Original author: zeljko.cavic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ProjekatRVA.Models
{
	public class Event {

		private string dateAndTime;
		private int id;
		private string text;
		public Planner planner;
		public int plannerId;
		private DateTime time;

		public Event(){

		}

		~Event(){

		}

		public string DateAndTime{
			get{
				return dateAndTime;
			}
			set{
				dateAndTime = value;
			}
		}

		public int Id{
			get{
				return id;
			}
			set{
				id = value;
			}
		}

		public string Text{
			get{
				return text;
			}
			set{
				text = value;
			}
		}

		public DateTime Time
		{
			get
			{
				return time;
			}
			set
			{
				time = value;
			}
		}

	}//end Event

}//end namespace EventPlanner