///////////////////////////////////////////////////////////
//  User.cs
//  Implementation of the Class User
//  Generated by Enterprise Architect
//  Created on:      25-Jul-2022 7:42:22 PM
//  Original author: zeljko.cavic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using ProjekatRVA.Enums;
using System.ComponentModel.DataAnnotations;
using ProjekatRVA.Models;

namespace ProjekatRVA.Models
{
	public class User {

		private int id;
		private string lastName;
		private string name;
		[MaxLength(450)]
		private string password;
		private string username;
		private bool isLoggedIn;
		private EUserType userType;
		public string token;

		public List<Planner> planners;

		public User(){

		}   

        ~User(){

		}

		public EUserType UserType
		{
			get
			{
				return userType;
			}
			set
			{
				userType = value;
			}
		}

		public int Id{
			get{
				return id;
			}
			set{
				id = value;
			}
		}

		public string LastName{
			get{
				return lastName;
			}
			set{
				lastName = value;
			}
		}

		public string Name{
			get{
				return name;
			}
			set{
				name = value;
			}
		}

		public string Password{
			get{
				return password;
			}
			set{
				password = value;
			}
		}

		public string Username{
			get{
				return username;
			}
			set{
				username = value;
			}
		}

		public bool IsLoggedIn
		{
			get
			{
				return isLoggedIn;
			}
			set
			{
				isLoggedIn = value;
			}
		}

	}//end User

}//end namespace EventPlanner